version: '3.8'

services:
  api:
    build: .
    container_name: portifolio-api
    ports:
      - "8085:8085"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=8085
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge